echo "Good morning, Michael"
echo "ALL YOUR BASE ARE BELONG TO US!!!!"

alias att="atom ."
alias gu="gem update"
alias gemc="gem cleanup"
alias nu="npm update"
alias plo="pip list --outdated"
alias piu="pip install --upgrade"
alias p3lo="pip3 list --outdated"
alias p3iu="pip3 install --upgrade"
alias au="apm update"
alias bu="brew update"
alias bo="brew outdated"
alias bup="brew upgrade -all"
alias bc="brew cleanup"
alias ll="ls -lathr"
alias exc="cd ~/coding/exercism_exercises/ruby"
alias ef="exercism fetch"
alias es="exercism submit"
alias el="exercism list"
alias pgstart="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
alias pgstop="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log stop"
alias fs="foreman start"

test -e ${HOME}/.iterm2_shell_integration.bash && source ${HOME}/.iterm2_shell_integration.bash
